import { makeStyles } from "@mui/styles";

export const useStyles = makeStyles(() => ({
  root: {
    backgroundColor: "#1e1f22",
    display: "block",
  },
  header: {
    position: "relative",
    top: 0,
    zIndex: 110,
    display: "flex",
    height: "64px",
    margin: "0 32px",
    alignItems: "center",
  },
  logo: {
    backgroundColor: "initial",
    outline: "none",
    cursor: "pointer",
    paddingRight: "32px",
    transition: "color .3s",
    boxSizing: "border-box",
    display: "flex",
  },
  logoImg: {
    width: "110px",
  },
  avatar: {
    padding: "8.5px 16px",
    cursor: "pointer",
    borderRadius: "18px",
    color: "#fff",
    fontFamily: "Poppins",
    fontSize: "13px",
    fontWeight: "500",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    "&:hover": {
      backgroundColor: "#ffffff1a",
      padding: "8.5px 16px",
    },
  },
  dropIcon: {
    marginLeft: "9px",
  },
  view: {
    display: "flex",
    flex: "1 1",
    justifyContent: "flex-end",
  },
  avatarTxt: {
    borderRadius: "4px",
    fontSize: "13px",
    background: "rgba(43,44,47,.05)",
    height: "40px",
    // -webkit-backdrop-filter: blur(4px),
    backdropFilter: "blur(4px)",
    cursor: "pointer",
    padding: "0 16px",
    display: "flex",
    alignItems: "center",
    color: "#fff",
    marginRight: "24px",
    backgroundColor: "#221ef5",
  },
  buttonGroup: {
    display: "flex",
    alignItems: "center",
  },
  register: {
    marginRight: "16px",
    fontSize: "13px",
    fontWeight: 500,
    lineHeight: "16px",
    cursor: "pointer",
    padding: "0",
    color: "#fff",
  },
  login: {
    height: "40px",
    paddingRight: "16px",
    paddingLeft: "16px",
    fontSize: "14px",
    color: "#f4f5f6",
    letterSpacing: ".3px",
    cursor: "pointer",
    background: "#2c7dfa",
    border: "none",
    borderRadius: "20px",
    outline: "none",
    whiteSpace: "nowrap",
    alignItems: "center",
    display: "flex",
  },
}));
